name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.0.0
        id: snake-gif
        with:
          github_user_name: ls1w
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
